version: "3"
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - .:/project
    working_dir: /project
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - .:/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - web
    privileged: true

volumes:
  db-store:
